### ISSUE TITLE
placeholder alignment

### ISSUE THREAD

**Issue by effectworks** [yabwe/medium-editor#661]
Is there a way to position the placeholders? Currently the placeholders are aligned to top and left without any padding. Attached image below for reference.
![screen shot 2015-06-01 at 6 32 53 pm](https://cloud.githubusercontent.com/assets/8318752/7913343/c0046a82-088c-11e5-88b0-1f992d3c8381.png)

**Comment by j0k3r** [comment]
You can add your own CSS to adjust it

```css
.medium-editor-placeholder:after {
    padding: 10px;
    margin: 10px;
}
```
